// <auto-generated />
using System;
using Coursework.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coursework.Persistence.Migrations
{
    [DbContext(typeof(CoursworkContext))]
    [Migration("20230405212916_modifyentities")]
    partial class modifyentities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Coursework.Domain.Entities.Candidate", b =>
                {
                    b.Property<Guid>("GID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserGID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GID");

                    b.HasIndex("UserGID");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.Recruiter", b =>
                {
                    b.Property<Guid>("GID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserGID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GID");

                    b.HasIndex("UserGID");

                    b.ToTable("Recruiters");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenGID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserGID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RefreshTokenGID");

                    b.HasIndex("UserGID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("GID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("GID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("GID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.Vacancy", b =>
                {
                    b.Property<Guid>("GID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RecruiterGID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<Guid>("VacancyStatusGID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GID");

                    b.HasIndex("RecruiterGID");

                    b.HasIndex("VacancyStatusGID");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.VacancySkill", b =>
                {
                    b.Property<Guid>("VacancyGID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillGID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VacancyGID", "SkillGID");

                    b.HasIndex("SkillGID");

                    b.ToTable("VacancySkills");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.VacancyStatus", b =>
                {
                    b.Property<Guid>("GID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GID");

                    b.ToTable("VacancyStatuses");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("Coursework.Domain.Entities.User", "User")
                        .WithMany("Candidates")
                        .HasForeignKey("UserGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Candidates_UserGID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.Recruiter", b =>
                {
                    b.HasOne("Coursework.Domain.Entities.User", "User")
                        .WithMany("Recruiters")
                        .HasForeignKey("UserGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Recruiters_UserGID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Coursework.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.Vacancy", b =>
                {
                    b.HasOne("Coursework.Domain.Entities.Recruiter", "Recruiter")
                        .WithMany("Vacancies")
                        .HasForeignKey("RecruiterGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vacancies_RecruiterGID");

                    b.HasOne("Coursework.Domain.Entities.VacancyStatus", "VacancyStatus")
                        .WithMany("Vacancies")
                        .HasForeignKey("VacancyStatusGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vacancies_VacancyStatusGID");

                    b.Navigation("Recruiter");

                    b.Navigation("VacancyStatus");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.VacancySkill", b =>
                {
                    b.HasOne("Coursework.Domain.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VacancySkills_SkillGID");

                    b.HasOne("Coursework.Domain.Entities.Vacancy", "Vacancy")
                        .WithMany()
                        .HasForeignKey("VacancyGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VacancySkills_VacancyGID");

                    b.Navigation("Skill");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.Recruiter", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.User", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Recruiters");
                });

            modelBuilder.Entity("Coursework.Domain.Entities.VacancyStatus", b =>
                {
                    b.Navigation("Vacancies");
                });
#pragma warning restore 612, 618
        }
    }
}
